# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  sendgrid_from_email: help@railway-mrkt.com
  sendgrid_from_name: "West Market"
  send_email: "true"

development:
  <<: *defaults
  secret_key_base: e1eb9e8f422a3ea7cf7fd7126c15b4d6f5681de180fd460774a465e8130c07ef5442a39ece96fd128313c3454265f1e3f3a97f43ebe604936a8568289786102
  domain: localhost:3000

test:
  <<: *defaults
  secret_key_base: a83ef50cc3752bda6d983cb91573bb86f1dbb37995769f3012222b70948f07e6fafe4ce177c09e6afb9f8a026fdc7848b4fffe08b0f282d9442a441f23c510fe
  domain: localhost:3000

integration:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain: radiant-dusk-26611.herokuapp.com

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain: radiant-dusk-26611.herokuapp.com
